version: "3.9"

services:
  bbwhereos_postgresql:
    container_name: bbwhereos_postgresql
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - bbwheroes_postgresql:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    env_file: ./.docker.env

volumes:
    bbwheroes_postgresql:
