version: "3.9"

services:
  bbwheroes_postgresql:
    container_name: bbwheroes_postgresql
    image: postgres:16-alpine
    volumes:
      - bbwheroes_postgresql:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    env_file: ./.docker.env
    networks:
      - bbwheroes

volumes:
    bbwheroes_postgresql:

networks:
  bbwheroes:
    external: true
