CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "github_id" int UNIQUE NOT NULL,
  "bbw_email" varchar(255) UNIQUE,
  "discord_id" varchar(255) UNIQUE
);

CREATE TABLE "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "repo_id" INT UNIQUE,
  "owner_id" int NOT NULL,
  "module" int NOT NULL,
  "teacher" varchar(255) NOT NULL,
  "task_name" varchar(255) NOT NULL,
  "slugified_task_name" varchar(255) NOT NULL,
  "username" varchar(255) NOT NULL,
  "open_proposal" bool NOT NULL DEFAULT false
);

CREATE TABLE "proposals" (
  "id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  "project_id" int NOT NULL,
  "type" varchar(255) NOT NULL,
  "data" json
);
